### ISSUE TITLE
XSRF-Tokens frontend

### ISSUE THREAD

**Issue by OGALEXI** [AnthonyBronca/FireBnB#130]
XSRF-Tokens are not being requested or stored in the frontend.

**Comment by AnthonyBronca** [comment]
To get the XSRF-Token, we currently have to ping `/api/csrf/restore` 

This fix by @OGALEXI  should allow users to get the proper token by default on the splash page.

**Comment by OGALEXI** [comment]
Done! About to submit pr, had to add a fetch in App.tsx
