### ISSUE TITLE
Fix spot detail page responsiveness

### ISSUE THREAD

**Issue by OGALEXI** [AnthonyBronca/FireBnB#173]

**Comment by OGALEXI** [comment]
Taking a tad bit longer than expected with that right side whitespace.

**Comment by OGALEXI** [comment]
Fixed the right side whitespace, adjusting image borders and resizing a bit

**Comment by OGALEXI** [comment]
Refactoring to grid

**Comment by AnthonyBronca** [comment]
![Screenshot 2023-11-17 at 6 52 24 PM](https://github.com/AnthonyBronca/FireBnB/assets/95654116/07c6f3c7-2658-40ac-a85e-25b73085eb69)

**Comment by AnthonyBronca** [comment]
Looks so good and the responsiveness to the white space.. chefs kiss
