### ISSUE TITLE
Spot detail images are lost on refresh

### ISSUE THREAD

**Issue by OGALEXI** [AnthonyBronca/FireBnB#181]

**Comment by AnthonyBronca** [comment]
This has been fixed! Thanks @OGALEXI  for pointing it out. 

The fix includes conditionals within a useEffect that can check if the data has already been stored in state or not. In the event that it is not, as is the case when you refresh on page, then it makes a fetch request to the backend to grab just the data for that one spot. This helps speed up the process of fetching one spot. 

Additionally, this fix updated the store to be normalized across grabbing one spot vs all spots. The backend querying was also updated to be more efficient and removed n + 1 queries
