### ISSUE TITLE
Create Mobile

### ISSUE THREAD

**Issue by AnthonyBronca** [AnthonyBronca/FireBnB#227]
- [x] Initialize project with Expo
- [x] Start React Native boiler plate
- [x] Add Redux (install Redux Toolkit)
- [x] Install Axios to use with Redux Toolkit
- [x] Add LocalTunnel
- [x] Add Navigation
- [x] Add assets
- [x] Add wireframes
- [x] Connect FontAwesome
- [x] Add AWS
- [x] Add Snack deployment
- [x] Add project kanban items

**Comment by AnthonyBronca** [comment]
- [ ] Initialize project with Expo
- [ ] Start React Native boiler plate
- [ ] Add Redux
- [ ] Add LocalTunnel
- [ ] Add Navigation
- [ ] Add assets
- [ ] Add wireframes
- [ ] Connect FontAwesome
- [ ] Add AWS

**Comment by AnthonyBronca** [comment]
- Created Nav, and added Bottom tabs. The bottoms still need to be adjusted with logos and functionaltiy
- Redux can be brought in from Web
- Started adding Constants and interfaces for global styling such as font and colors
- Structure of folder created ( Having a screen folder with each screen having its own component folder)
- Will also be adding a global component folder for components that are reused

**Comment by AnthonyBronca** [comment]
Order of things to be completed:
1.  Add assets so that we can have bottom tabs made
2. Connect FontAwesome so that we use some of those icons for things like search icon on splash page
3. Deploy to snacks
4. Add Redux
5. Add localtunnel, with automation so that on "npm start" it runs a sh script that can give us auto port connection to backend localhost 8000 (this should only be done when on dev, and not in prod)
6. Add AWS incorporated with the redux store
7. Finish adding Kanban items (we can do this as a group)

**Comment by kryskimmel** [comment]
- Connected FontAwesome and updated the tabs of the bottom navigation bar with nearly identical icons to the original application.
- Added some wireframes to the wireframes directory (within the assets directory).

**Comment by kryskimmel** [comment]
- Installed aws-sdk and expo-image-picker. Modified the "Test.tsx" component to test expo-image-picker, which I was able to try multiple image selection and single image selection with a maximum of 6 images. Having images sent to an AWS S3 bucket is still in progress.
