### ISSUE TITLE
Flickering Heart

### ISSUE THREAD

**Issue by AnthonyBronca** [AnthonyBronca/FireBnB#267]
Heart flickers on Mobile for click.

Consider using caching such as a map that will allow for us to change state quicker for just the one component that needs to be adjusted.

**Comment by kryskimmel** [comment]
- The heart icon placed on the front layer of each spot image tile on the splash page no longer flickers when pressed on. Heart icon still requires functionality to add a favorited spot to the wishlist; however, heart color now immediately switches between #FF385B and #535350 if pressed.

**Comment by AnthonyBronca** [comment]
Looks good!
