### ISSUE TITLE
Some styling on regular Iphone 15

### ISSUE THREAD

**Issue by AnthonyBronca** [AnthonyBronca/FireBnB#269]
Some of the splash page items are close to the edges. Maybe some marginHorizontal of about 10-20 to push everything in a little bit.

**Comment by kryskimmel** [comment]
- Adjusted alignment of splash page items by applying horizontal margins on the spot image, spots details container, heart icon, and "Guest favorite" text. Items are no longer clipped when viewing splash page on an iPhone 15.

**Comment by AnthonyBronca** [comment]
Looks good!
